name = "smol-textures"
main = "src/worker.ts"
compatibility_date = "2025-01-01"

[[r2_buckets]]
binding = "STATIC_FILES"
bucket_name = "smolglb"

# Custom domain routes
routes = [
  { pattern = "smolglb.com/*", zone_name = "smolglb.com" },
  { pattern = "www.smolglb.com/*", zone_name = "smolglb.com" }
]

[vars]
# Add any environment variables here

[env.production]
name = "smol-textures" 
